name: Failsafe Simulator Build

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        check: [
          "failsafe_web",
        ]
    container:
      image: alexander738/px4-dev-nuttx-noble:2025-02-10
      options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
    steps:
      - name: Install Node v20.18.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install empscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git _emscripten_sdk
          cd _emscripten_sdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Testing [${{ matrix.check }}]
        run: |
          . ./_emscripten_sdk/emsdk_env.sh
          git config --global --add safe.directory '*'
          make ${{ matrix.check }}
