name: FLASH usage analysis

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  analyze_flash:
    name: FLASH usage analysis
    runs-on: ubuntu-latest
    container:
      image: px4io/px4-dev-nuttx-focal
    strategy:
      matrix:
        target: [px4_fmu-v5x, px4_fmu-v6x]
    outputs:
      px4_fmu-v5x-bloaty-output-encoded: ${{ steps.gen-output.outputs.px4_fmu-v5x-bloaty-output-encoded }}
      px4_fmu-v5x-bloaty-total-file-percentage: ${{ steps.gen-output.outputs.px4_fmu-v5x-bloaty-total-file-percentage }}
      px4_fmu-v5x-bloaty-total-file-absolute: ${{ steps.gen-output.outputs.px4_fmu-v5x-bloaty-total-file-absolute }}
      px4_fmu-v5x-bloaty-total-vm-percentage: ${{ steps.gen-output.outputs.px4_fmu-v5x-bloaty-total-vm-percentage }}
      px4_fmu-v5x-bloaty-total-vm-absolute: ${{ steps.gen-output.outputs.px4_fmu-v5x-bloaty-total-vm-absolute }}
      px4_fmu-v6x-bloaty-output-encoded: ${{ steps.gen-output.outputs.px4_fmu-v6x-bloaty-output-encoded }}
      px4_fmu-v6x-bloaty-total-file-percentage: ${{ steps.gen-output.outputs.px4_fmu-v6x-bloaty-total-file-percentage }}
      px4_fmu-v6x-bloaty-total-file-absolute: ${{ steps.gen-output.outputs.px4_fmu-v6x-bloaty-total-file-absolute }}
      px4_fmu-v6x-bloaty-total-vm-percentage: ${{ steps.gen-output.outputs.px4_fmu-v6x-bloaty-total-vm-percentage }}
      px4_fmu-v6x-bloaty-total-vm-absolute: ${{ steps.gen-output.outputs.px4_fmu-v6x-bloaty-total-vm-absolute }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Git ownership workaround
        run: git config --system --add safe.directory '*'

      - name: Build
        run: make ${{ matrix.target }}

      - name: Store the ELF with the change
        run: cp ./build/${{ matrix.target }}_default/${{ matrix.target }}_default.elf ./with-change.elf

      - name: Clean previous build
        run: |
          make clean
          make distclean

      - name: If it's a PR checkout the base commit
        if: ${{ github.event.pull_request }}
        run: git checkout ${{ github.event.pull_request.base.sha }}

      - name: If it's a push checkout the previous commit
        if: github.event_name == 'push'
        run: git checkout ${{ github.event.before }}

      - name: Update submodules
        run: make submodulesupdate

      - name: Build
        run: make ${{ matrix.target }}

      - name: Store the ELF before the change
        run: cp ./build/${{ matrix.target }}_default/${{ matrix.target }}_default.elf ./before-change.elf

      - name: bloaty-action
        uses: PX4/bloaty-action@v1.0.0
        id: bloaty-step
        with:
          bloaty-args: -d sections,compileunits -s vm -n 0 ./with-change.elf -- ./before-change.elf
          output-to-summary: true

      - name: Generate output
        id: gen-output
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "${{ matrix.target }}-bloaty-output-encoded<<$EOF" >> $GITHUB_OUTPUT
          echo "${{ steps.bloaty-step.outputs.bloaty-output-encoded }}" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          echo "${{ matrix.target }}-bloaty-total-file-percentage=${{ steps.bloaty-step.outputs.bloaty-total-file-percentage }}" >> "$GITHUB_OUTPUT
          echo "${{ matrix.target }}-bloaty-total-file-absolute=${{ steps.bloaty-step.outputs.bloaty-total-file-absolute }}" >> "$GITHUB_OUTPUT
          echo "${{ matrix.target }}-bloaty-total-vm-percentage=${{ steps.bloaty-step.outputs.bloaty-total-vm-percentage }}" >> "$GITHUB_OUTPUT
          echo "${{ matrix.target }}-bloaty-total-vm-absolute=${{ steps.bloaty-step.outputs.bloaty-total-vm-absolute }}" >> "$GITHUB_OUTPUT

  post_pr_comment:
    name: Post PR comment
    runs-on: ubuntu-latest
    needs: [analyze_flash]
    steps:
      - name: If it's a PR add a comment with the bloaty output
        if: ${{ github.event.pull_request }}
        uses: actions/github-script@v6
        with:
          script: |
            const comment = [
               '## FLASH Analysis',
               '<details>',
               '<summary>px4_fmu-v5x (${{ needs.analyze_flash.outputs.px4_fmu-v5x-bloaty-total-vm-absolute }})</summary>',
               '',
               '```',
               `${{ needs.analyze_flash.outputs.px4_fmu-v5x-bloaty-output-encoded }}`,
               '```',
               '</details>',
               '',
               '<details>',
               '<summary>px4_fmu-v6x (${{ needs.analyze_flash.outputs.px4_fmu-v6x-bloaty-total-vm-absolute }})</summary>',
               '',
               '```',
               `${{ needs.analyze_flash.outputs.px4_fmu-v6x-bloaty-output-encoded }}`,
               '```',
               '</details>'
            ]
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment.join('\n')
            })
